### ISSUE TITLE
cannot run benchmark_lasso in local

### ISSUE THREAD

**Issue by Clej** [benchopt/benchOpt#122]
I am trying to run the benchmark_lasso within my conda env named `my_optim_env`.

I installed benchopt within this environment with `pip install benchopt`. With `conda list`, I checked and benchopt does appear installed in this env. I also installed dependencies e.g Scipy, Numpy. I have cloned benchmark_lasso to a specific directory `.../optimization/`.
Then, within `my_optim_env` (with Miniconda3), I went to the directory where benchmark_lasso was cloned and entered `benchopt run -l ../optimization/benchmark_lasso` to run it in local but it returned the following error:

`Traceback (most recent call last):
  File "c:\users\...\miniconda3\envs\my_optim_env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\...\miniconda3\envs\my_optim_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\Miniconda3\envs\my_optim_env\Scripts\benchopt.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'benchopt'`

So it seems that whatever I try to do, the command `benchopt` is not recognized by conda.
Am I doing something wrongly ?
I have checked that benchopt.exe exists is in this env (under directory `/Scripts/`).
I apologize the issue seems to be really basic. I also tried with the windows shell, the output error is the same.
Could you please some help to solve it ?

conda version: 4.8.3. Python version: 3.6.12

**Comment by Clej** [comment]
Sorry my mistake, there might have been a dependency conflict in my env. In a new environment I did bot face the issue.
