### ISSUE TITLE
BUG: issue with pacakges installed from conda-forge in the Lasso bench

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#241]
this bug happens in the lasso benchmark but I believe it's a benchopt issue. 

It seems conda does not use conda-forge as a channel inside the env (thus it fails to find glum and others):

```
(benchopt_benchmark_lasso) ➜  benchmark_lasso git:(main) conda config --show channels
channels:
  - defaults
```

Here the full stacktrace

```bash
(base) ➜  benchmark_lasso git:(main) BENCHOPT_DEBUG=1 benchopt install . --env --recreate
Installing 'benchmark_lasso' requirements
Creating conda env 'benchopt_benchmark_lasso':...
conda env config:
----------------------------------------
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - numpy
  - cython
  - compilers
  - pip
  - pip:
    - -e /home/mathurin/workspace/benchopt
----------------------------------------
------------------------------------------------------------
set -e
conda env create --force -n benchopt_benchmark_lasso -f /tmp/conda_env_l616bqj9.yml
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt --version --check-editable
------------------------------------------------------------
 done
# Install
Collecting packages:
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/blitz.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/cd.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/celer.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/cyanure.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/glmnet.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/glum.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/julia_pgd.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/l_bfgs_b.py Solver
------------------------------------------------------------
- 'L-BFGS-B' already available in 'benchopt_benchmark_lasso'
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/lightning.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/modopt_fista.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/modopt_pogm.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/python_pgd.py Solver
------------------------------------------------------------
- 'Python-PGD' already available in 'benchopt_benchmark_lasso'
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/r_pgd.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/sklearn.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/solvers/spams.py Solver
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/datasets/finance.py Dataset
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/datasets/leukemia.py Dataset
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/datasets/libsvm.py Dataset
------------------------------------------------------------
------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
benchopt check-install /home/mathurin/workspace/benchopt/benchmarks/benchmark_lasso/datasets/simulated.py Dataset
------------------------------------------------------------
- 'Simulated' already available in 'benchopt_benchmark_lasso'
... done
Installing required packages for:
- Blitz
- cd
- Celer
- Cyanure
- glmnet
- glum
- Julia-PGD
- Lightning
- ModOpt-FISTA
- ModOpt-POGM
- R-PGD
- sklearn
- spams
- finance
- leukemia
- libsvm
...------------------------------------------------------------
set -e
# Setup conda
unset R_HOME
eval "$(conda shell.bash hook)"
conda activate benchopt_benchmark_lasso

# Run script
conda install --update-all -y mkl rpy2 scikit-learn numba r-glmnet r-base julia python-spams glum
pip install libsvmdata git+https://github.com/CEA-COSMIC/ModOpt.git julia git+https://github.com/scikit-learn-contrib/lightning.git git+https://github.com/tbjohns/blitzl1.git@master cyanure-mkl celer
------------------------------------------------------------
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - glum
  - python-spams
  - julia

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Traceback (most recent call last):
  File "/home/mathurin/anaconda3/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mathurin/workspace/benchopt/benchopt/cli/main.py", line 274, in install
    benchmark.install_all_requirements(
  File "/home/mathurin/workspace/benchopt/benchopt/benchmark.py", line 233, in install_all_requirements
    install_in_conda_env(
  File "/home/mathurin/workspace/benchopt/benchopt/utils/conda_env_cmd.py", line 181, in install_in_conda_env
    _run_shell_in_conda_env(
  File "/home/mathurin/workspace/benchopt/benchopt/utils/shell_cmd.py", line 130, in _run_shell_in_conda_env
    return _run_shell(
  File "/home/mathurin/workspace/benchopt/benchopt/utils/shell_cmd.py", line 68, in _run_shell
    raise RuntimeError(raise_on_error.format(output=output))
RuntimeError: Failed to conda install packages ('pip:libsvmdata', 'pip:git+https://github.com/CEA-COSMIC/ModOpt.git', 'mkl', 'rpy2', 'pip:julia', 'pip:git+https://github.com/scikit-learn-contrib/lightning.git', 'scikit-learn', 'numba', 'pip:git+https://github.com/tbjohns/blitzl1.git@master', 'r-glmnet', 'r-base', 'julia', 'python-spams', 'pip:cyanure-mkl', 'pip:celer', 'glum')
Error:
(base) ➜  benchmark_lasso git:(main) 
```

**Comment by agramfort** [comment]
I suspect ModOpt <https://github.com/CEA-COSMIC/ModOpt.git> here as it
forces certain versions of numpy etc.

>

**Comment by mathurinm** [comment]
I don't think so, it fails when I try to install only glum, and the error message is really that it can't find the package (because it's not in conda defaults, only in conda-forge)

```(benchopt_benchmark_lasso) ➜  benchmark_lasso git:(main) benchopt install --env . -s glum
Installing 'benchmark_lasso' requirements
Conda env benchopt_benchmark_lasso already exists. Checking setup ...done
# Install
Collecting packages:
- 'Simulated' already available in 'benchopt_benchmark_lasso'
... done
Installing required packages for:
- glum
- finance
- leukemia
- libsvm
...Traceback (most recent call last):
  File "/home/mathurin/anaconda3/envs/benchopt_benchmark_lasso/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/mathurin/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mathurin/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mathurin/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mathurin/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mathurin/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mathurin/workspace/benchopt/benchopt/cli/main.py", line 274, in install
    benchmark.install_all_requirements(
  File "/home/mathurin/workspace/benchopt/benchopt/benchmark.py", line 233, in install_all_requirements
    install_in_conda_env(
  File "/home/mathurin/workspace/benchopt/benchopt/utils/conda_env_cmd.py", line 181, in install_in_conda_env
    _run_shell_in_conda_env(
  File "/home/mathurin/workspace/benchopt/benchopt/utils/shell_cmd.py", line 130, in _run_shell_in_conda_env
    return _run_shell(
  File "/home/mathurin/workspace/benchopt/benchopt/utils/shell_cmd.py", line 68, in _run_shell
    raise RuntimeError(raise_on_error.format(output=output))
RuntimeError: Failed to conda install packages ('scikit-learn', 'pip:libsvmdata', 'glum')
Error:Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - glum

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by tomMoral** [comment]
Yeah the issue it that the channels are not the right one:
```
Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```
I don't get it, we create the conda env using channels `conda-forge` and `nodefaults` to make sure we get only packages from `conda-forge`. This is the conda nightmare ^^.
What is your version of `conda` @mathurinm ?

**Comment by mathurinm** [comment]
```
(benchopt_benchmark_lasso) ➜  doc git:(pass_doc) ✗ conda --version
conda 4.11.0
```

**Comment by tomMoral** [comment]
Could you try to create the env like this and check that the channels are the right ones?

```
echo 'channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - numpy
  - cython
  - compilers
  - pip' > env.yml
conda env create -n test -f env.yml
conda activate test
conda info
```

**Comment by mathurinm** [comment]
It **installs** the dependencies through conda-forge,:
```
(test) ➜  doc git:(pass_doc) ✗ conda list    
# packages in environment at /home/mathurin/anaconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
```
 but it does not set this choice for the future installs in the environment: 
 
 ```
 (test) ➜  doc git:(pass_doc) ✗ conda config --show channels
channels:
  - defaults
```
I'll check how to do it
