### ISSUE TITLE
BUG? Cannot publish benchmark without the f flag.

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#262]
The doc says:
```
  -f, --filename TEXT  Specify the file to publish in the benchmark. If it is
                       not specified, take the latest one in the benchmark
                       output folder
```

But publishing without the `-f` flag gives me:

```
`(base) ➜  lasso git:(jolars/main) ✗ benchopt publish . -t <mygithubtoken>                 
Traceback (most recent call last):
  File "/home/mathurin/anaconda3/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mathurin/workspace/benchopt/benchopt/cli/process_results.py", line 100, in publish
    publish_result_file(benchmark.name, result_filename, token)
  File "/home/mathurin/workspace/benchopt/benchopt/utils/github.py", line 60, in publish_result_file
    repo.create_file(git_path, f"RESULT upload {file_name}",
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/github/Repository.py", line 2090, in create_file
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
```

with the -f flag and the same token:
```
benchopt publish . -t <mygithubtoken> -f outputs/lasso_benchopt_run_2021-12-08_10h10m02.html
Uploaded file lasso_benchopt_run_2021-12-08_10h10m02.html in benchopt/results
```

**Comment by agramfort** [comment]
if your token is in config and you do:

benchopt publish .


it works?
