### ISSUE TITLE
Better message for install and import failure

### ISSUE THREAD

**Issue by TomDLT** [benchopt/benchOpt#27]
- Running the benchmark, both `cvxpy` and `cyanure` seem to fail at import, but the error is caught by `safe_import`. The error messages are not informing of the import error. I wonder why you use `safe_import`, and if it would not be more informative to raise an ImportError.
- The corresponding installing steps could also report the failure, like
 `Installing cvxpy in lasso:... failed`.

**Traceback:**
```pytb
Creating venv lasso:... done
Installing Boston in lasso:... done
Installing finance in lasso:... done
Installing Blitz in lasso:... done
Installing cd in lasso:... done
Installing Celer in lasso:... done
Installing cvxpy in lasso:... done
Installing Cyanure in lasso:... done
Installing Lightning in lasso:... done
Boston
|--Lasso regression(reg=0.05)
|----Baseline(use_acceleration=false): done               
|----Baseline(use_acceleration=true): done                
|----Blitz: done                                          
/home/tom/work/github/benchOpt/benchmarks/lasso/solvers/cd.py:60: NumbaPerformanceWarning: '@' is faster on contiguous arrays, called on (array(float64, 1d, A), array(float64, 1d, C))
  w[j] = st(w[j] + X[:, j] @ R / L[j], lmbd / L[j])
/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/numba/typing/npydecl.py:958: NumbaPerformanceWarning: '@' is faster on contiguous arrays, called on (array(float64, 1d, A), array(float64, 1d, C))
  warnings.warn(NumbaPerformanceWarning(msg))
|----Cd: done                                             
|----Celer: done                                          
|----Cvxpy: failed                                        
Traceback (most recent call last):
  File "/home/tom/work/github/benchOpt/benchopt/runner.py", line 131, in run_one_solver
    sample_curve, objective_value = run_one_sample(
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 568, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 734, in call
    output = self.func(*args, **kwargs)
  File "/home/tom/work/github/benchOpt/benchopt/runner.py", line 81, in run_one_sample
    cost, objective_value = run_repetition(*args)
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 568, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 734, in call
    output = self.func(*args, **kwargs)
  File "/home/tom/work/github/benchOpt/benchopt/runner.py", line 53, in run_repetition
    solver.set_objective(**objective.to_dict())
  File "/home/tom/work/github/benchOpt/benchmarks/lasso/solvers/cvxpy.py", line 23, in set_objective
    self.beta = cp.Variable(n_features)
NameError: name 'cp' is not defined
|----Cyanure: failed                                      
Traceback (most recent call last):
  File "/home/tom/work/github/benchOpt/benchopt/runner.py", line 131, in run_one_solver
    sample_curve, objective_value = run_one_sample(
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 568, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 734, in call
    output = self.func(*args, **kwargs)
  File "/home/tom/work/github/benchOpt/benchopt/runner.py", line 81, in run_one_sample
    cost, objective_value = run_repetition(*args)
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 568, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/tom/work/github/benchOpt/.venv/lasso/lib/python3.8/site-packages/joblib/memory.py", line 734, in call
    output = self.func(*args, **kwargs)
  File "/home/tom/work/github/benchOpt/benchopt/runner.py", line 53, in run_repetition
    solver.set_objective(**objective.to_dict())
  File "/home/tom/work/github/benchOpt/benchmarks/lasso/solvers/cyanure.py", line 21, in set_objective
    self.solver = Regression(loss='square', penalty='l1',
NameError: name 'Regression' is not defined
```

**Comment by agramfort** [comment]
decision for @tomMoral
