### ISSUE TITLE
Make `click>=8.0` a requirement for Benchopt

### ISSUE THREAD

**Issue by PABannier** [benchopt/benchopt#280]
It seems that this issue:

```
Traceback (most recent call last):
  File "/home/qbe/anaconda3/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/qbe/anaconda3/bin/benchopt", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/qbe/anaconda3/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/home/qbe/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qbe/benchOpt/benchopt/cli/__init__.py", line 5, in <module>
    from benchopt.cli.main import main
  File "/home/qbe/benchOpt/benchopt/cli/main.py", line 96, in <module>
    env_name='False'):
  File "/home/qbe/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/qbe/anaconda3/lib/python3.7/site-packages/click/core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'shell_complete'
```

Can be solved by running `pip install click==8.0`. 

Maybe, `click==8.0` should be made a requirement for benchopt.

**Comment by agramfort** [comment]
Ok for >= but not ==

**Comment by mathurinm** [comment]
turns out we have it already and it's just a small typo in `setup.cfg`, we require >=0.8 instead of 8.0
