### ISSUE TITLE
Issue when rendering HTML report

### ISSUE THREAD

**Issue by PABannier** [benchopt/benchopt#283]
I'm running into an issue when generating the HTML report:

```
Writing results to outputs/benchmark_multi_task_lasso_benchopt_run_2021-12-22_15h42m48.html
Traceback (most recent call last):
  File "/Users/pierre-antoine/opt/miniconda3/envs/benchopt/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/Users/pierre-antoine/opt/miniconda3/envs/benchopt/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pierre-antoine/opt/miniconda3/envs/benchopt/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/pierre-antoine/opt/miniconda3/envs/benchopt/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pierre-antoine/opt/miniconda3/envs/benchopt/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pierre-antoine/opt/miniconda3/envs/benchopt/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/pierre-antoine/Documents/benchopt/benchopt/cli/main.py", line 113, in run
    run_benchmark(
  File "/Users/pierre-antoine/Documents/benchopt/benchopt/runner.py", line 471, in run_benchmark
    plot_benchmark(save_file, benchmark, html=html)
  File "/Users/pierre-antoine/Documents/benchopt/benchopt/plotting/__init__.py", line 47, in plot_benchmark
    plot_benchmark_html(fname, benchmark, kinds, display)
  File "/Users/pierre-antoine/Documents/benchopt/benchopt/plotting/generate_html.py", line 435, in plot_benchmark_html
    rendered = render_benchmark(
  File "/Users/pierre-antoine/Documents/benchopt/benchopt/plotting/generate_html.py", line 310, in render_benchmark
    return Template(
  File "/Users/pierre-antoine/opt/miniconda3/envs/benchopt/lib/python3.8/site-packages/mako/template.py", line 473, in render
    return runtime._render(self, self.callable_, args, data)
  File "/Users/pierre-antoine/opt/miniconda3/envs/benchopt/lib/python3.8/site-packages/mako/runtime.py", line 878, in _render
    _render_context(
  File "/Users/pierre-antoine/opt/miniconda3/envs/benchopt/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/pierre-antoine/opt/miniconda3/envs/benchopt/lib/python3.8/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "_Users_pierre_antoine_Documents_benchopt_benchopt_plotting_html_templates_benchmark_mako_html", line 43, in render_body
KeyError: 'sysinfo'
```

It seems to be related to the `Mako` package. I tried upgrading Mako to 1.1.6, downgrading it to versions 1.1.5 and 1.1.4.
I also tried creating a fresh environment with Python 3.8, but I still run into the same issue.

I have found no documented issue about a similar error on Mako.

**Comment by PABannier** [comment]
Cleaning the `outputs` folder did the trick for me.

**Comment by mathurinm** [comment]
@qb3 encountered the problem a while ago, removing the `outputs` folder fixed the issue. It just worked for @PABannier  too. 
Apparently the problem stemmed from upgrading benchopt

**Comment by mathurinm** [comment]
@PABannier should we close?

**Comment by PABannier** [comment]
For the record, cleaning the `outputs` folder did the trick for me.
Closing because solved.
