### ISSUE TITLE
BUG? CLI tool claims benchopt is not installed in env while it is

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#295]
```
(base) ➜  lasso git:(approx) ✗ benchopt install . --env-name tmpp -f -s apcd   
Installing 'lasso' requirements
Conda env tmpp already exists. Checking setup ... 
Traceback (most recent call last):
  File "/home/mathurin/anaconda3/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mathurin/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mathurin/workspace/benchopt/benchopt/cli/main.py", line 280, in install
    create_conda_env(env_name, recreate=recreate, quiet=quiet)
  File "/home/mathurin/workspace/benchopt/benchopt/utils/conda_env_cmd.py", line 73, in create_conda_env
    raise RuntimeError(
RuntimeError: `benchopt` is not installed in existing env 'tmpp'. This can lead to unexpected behavior. You can correct this by either using the --recreate option or installing benchopt in conda env tmpp.
(base) ➜  lasso git:(approx) ✗ conda activate tmpp
(tmpp) ➜  lasso git:(approx) ✗ benchopt
Usage: benchopt [OPTIONS] COMMAND [ARGS]...

  Command-line interface to benchOpt

Options:
  -v, --version  Print version
  -h, --help     Show this message and exit.

Commands:
  clean             Clean the cache and the outputs from a benchmark.
  config            Configuration helper for benchopt.
  generate-results  Generate result website from list of benchmarks.
  install           Install the requirements (solvers/datasets) for a...
  plot              Plot the result from a previously run benchmark.
  publish           Publish the result from a previously run benchmark.
  ```

**Comment by mathurinm** [comment]
I can no longer reproduce, closing
