### ISSUE TITLE
Conda env not found

### ISSUE THREAD

**Issue by zaccharieramzi** [benchopt/benchopt#307]
I have the following error when running `benchopt run -e .`:

```
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Traceback (most recent call last):
  File "/home/zaccharie/workspace/benchmark_resnet_classif/venv/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/zaccharie/workspace/benchmark_resnet_classif/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/zaccharie/workspace/benchmark_resnet_classif/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/zaccharie/workspace/benchmark_resnet_classif/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zaccharie/workspace/benchmark_resnet_classif/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zaccharie/workspace/benchmark_resnet_classif/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/cli/main.py", line 155, in run
    raise RuntimeError(
RuntimeError: The default env 'benchopt_benchmark_resnet_classif' for benchmark benchmark_resnet_classif does not exist. Make sure to run `benchopt install -e .` to create the benchmark and install the dependencies.
```

However, `conda env list` returns:

```
# conda environments:
#
base                  *  /home/zaccharie/anaconda3
benchopt_benchmark_lasso     /home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso
benchopt_benchmark_resnet_classif     /home/zaccharie/anaconda3/envs/benchopt_benchmark_resnet_classif
```

And I did run `benchopt install -e .` without problems (except https://github.com/benchopt/benchopt/issues/305 when using the pypi version).

**Comment by agramfort** [comment]
weird... for now I would say run in the local environment

**Comment by zaccharieramzi** [comment]
Actually it might be more that you have to be in a conda environment before running anything: `conda activate base`.

**Comment by jolars** [comment]
I ran into this issue as well and I am on conda 4.11. Running `conda activate base` before calling `benchopt run` solved the problem. Perhaps it should be mentioned in the docs?
