### ISSUE TITLE
Bug with benchopt run

### ISSUE THREAD

**Issue by EnLAI111** [benchopt/benchopt#310]
When I run the commande with anaconda prompt in Windows ```benchopt run```, it can't work. After using ipdb for a slover, I found the problem is from here.
```
d:\anaconda\anaconda3\lib\site-packages\benchopt\runner.py(77)run_one_resolution()
info = get_sys_info()
```
Then this line.
```
d:\anaconda\anaconda3\lib\site-packages\benchopt\utils\sys_info.py(93)get_sys_info()
info["version-numpy"] = (np.__version__, _get_numpy_libs())
```
Then this one.
```
d:\anaconda\anaconda3\lib\site-packages\benchopt\utils\sys_info.py(44)_get_numpy_libs()
with SuppressStd() as capture:
```
And at last this function,
```
d:\anaconda\anaconda3\lib\tempfile.py(473)func_wrapper()
    472             def func_wrapper(*args, **kwargs):
--> 473                 return func(*args, **kwargs)
    474             # Avoid closing the file as long as the wrapper is alive,

ipdb> s
--Return--
6
d:\anaconda\anaconda3\lib\tempfile.py(473)func_wrapper()
    472             def func_wrapper(*args, **kwargs):
--> 473                 return func(*args, **kwargs)
    474             # Avoid closing the file as long as the wrapper is alive,

ipdb> func
<built-in method fileno of _io.BufferedRandom object at 0x000002017CFD7930>
ipdb> s
Traceback (most recent call last):
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\utils\pdb_helpers.py", line 25, in exception_handler
    yield
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\runner.py", line 303, in run_one_solver
    curve_one_rep, status = run_one_to_cvg_cached(
  File "d:\anaconda\anaconda3\lib\site-packages\joblib\memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "d:\anaconda\anaconda3\lib\site-packages\joblib\memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "d:\anaconda\anaconda3\lib\site-packages\joblib\memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\runner.py", line 125, in run_one_to_cvg
    cost = run_one_resolution_cached(stop_val=stop_val, **call_args)
  File "d:\anaconda\anaconda3\lib\site-packages\joblib\memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "d:\anaconda\anaconda3\lib\site-packages\joblib\memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "d:\anaconda\anaconda3\lib\site-packages\joblib\memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\runner.py", line 77, in run_one_resolution
    info = get_sys_info()
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\utils\sys_info.py", line 93, in get_sys_info
    info["version-numpy"] = (np.__version__, _get_numpy_libs())
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\utils\sys_info.py", line 44, in _get_numpy_libs
    with SuppressStd() as capture:
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\utils\stream_redirection.py", line 24, in __enter__
    os.dup2(self.tfile.fileno(), self.orig_stderr_fileno)
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\utils\stream_redirection.py", line 24, in __enter__
    os.dup2(self.tfile.fileno(), self.orig_stderr_fileno)
  File "d:\anaconda\anaconda3\lib\bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "d:\anaconda\anaconda3\lib\bdb.py", line 112, in dispatch_line
    self.user_line(frame)
  File "d:\anaconda\anaconda3\lib\pdb.py", line 262, in user_line
    self.interaction(frame, None)
  File "d:\anaconda\anaconda3\lib\site-packages\IPython\core\debugger.py", line 319, in interaction
    OldPdb.interaction(self, frame, traceback)
  File "d:\anaconda\anaconda3\lib\pdb.py", line 356, in interaction
    self.print_stack_entry(self.stack[self.curindex])
  File "d:\anaconda\anaconda3\lib\site-packages\IPython\core\debugger.py", line 381, in print_stack_entry
    print(self.format_stack_entry(frame_lineno, '', context), file=self.stdout)
  File "d:\anaconda\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "d:\anaconda\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "d:\anaconda\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "d:\anaconda\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\Anaconda3\Scripts\benchopt.exe\__main__.py", line 7, in <module>
    sys.exit(benchopt())
  File "d:\anaconda\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "d:\anaconda\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\cli\main.py", line 123, in run
    run_benchmark(
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\runner.py", line 448, in run_benchmark
    run_statistics.extend(run_one_solver(
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\runner.py", line 303, in run_one_solver
    curve_one_rep, status = run_one_to_cvg_cached(
  File "d:\anaconda\anaconda3\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\utils\pdb_helpers.py", line 32, in exception_handler
    print_normalize(f"{tag} {status}")
  File "d:\anaconda\anaconda3\lib\site-packages\benchopt\utils\colorify.py", line 37, in print_normalize
    print(msg)
  File "d:\anaconda\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "d:\anaconda\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "d:\anaconda\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "d:\anaconda\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid.

If you suspect this is an IPython 7.22.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Exception ignored in: <colorama.ansitowin32.StreamWrapper object at 0x000002017D603BB0>
OSError: [WinError 6] The handle is invalid.
```

Env:

Python 3.8.8
```benchopt``` installed from source
conda 4.12.0

Thank you!

**Comment by mathurinm** [comment]
Hello @EnLAI111 :) 

To help us solve this issue, can you please show the exact command you type to obtain the error (`benchopt run` would not work, you would need `benchopt run .` for example). 
Can you also show the full stacktrace that you get as a result of this command ?
Thanks a lot 

PS: see how I have edited your message with code blocks between triple backticks (```) to format code in a nice fashion

**Comment by EnLAI111** [comment]
Sorry for being not so clear about the bug.

When I run ```benchopt run benchmark_tv_1d``` in the anaconda prompt, there is no error, but actually the ```benchopt``` hasn't work.

'''
d:\anaconda\anaconda3\lib\site-packages\benchopt\config.py:74: UserWarning: BenchOpt config file C:\Users\Rime\.config\benchopt.ini is with mode 666.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
Benchopt is running
Simulated[n_samples=1000,n_features=500]                                                                                
|--Ordinary Least Squares[fit_intercept=False]                                                                          
[1;34m|----GD[use_acceleration=False]:[0m initialization (1 / 5 reps)                                                 d:\anaconda\anaconda3\lib\site-packages\benchopt\config.py:74: UserWarning: BenchOpt config file C:\Users\Rime\.config\benchopt.ini is with mode 666.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
DEBUG - Calling solver GD[use_acceleration=False] with stop val: 0
'''

So I have used ```ipdb``` for the ``solver``` to see where the problem comes from. And then I found the error that I posted in the question.

**Comment by tomMoral** [comment]
A way to solve this issue would be to make sure that `get_sys_info` always returns something, even on exotic system, with a warning when it does not work.

**Comment by mathurinm** [comment]
actually on @Badr-Moufad 's machine, SuppressStd fails (kills the process) without throwing an exception, so returning a defaultdict `info` did not fix the issue on our side
