### ISSUE TITLE
Error when using mamba to install

### ISSUE THREAD

**Issue by zaccharieramzi** [benchopt/benchopt#336]
I am trying to use `mamba` as the conda command to install packages.
I did the following:
```
conda install -c conda-forge mamba
benchopt config set conda_cmd mamba
```

And when I run `benchopt test . --env-name bench_test_env -vl` in [this PR](https://github.com/benchopt/benchmark_resnet_classif/pull/8), I obtain the following error:

```
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
Conda env bench_test_env already exists. Checking setup ... /home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
Traceback (most recent call last):
  File "/home/zaccharie/anaconda3/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/zaccharie/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/zaccharie/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/zaccharie/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zaccharie/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zaccharie/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/cli/main.py", line 330, in test
    create_conda_env(env_name, with_pytest=True)
  File "/home/zaccharie/workspace/benchOpt/benchopt/utils/conda_env_cmd.py", line 70, in create_conda_env
    env_version, editable_install = get_benchopt_version_in_env(env_name)
  File "/home/zaccharie/workspace/benchOpt/benchopt/utils/conda_env_cmd.py", line 162, in get_benchopt_version_in_env
    benchopt_version, is_editable = output.split()
ValueError: too many values to unpack (expected 2)
```

**Comment by zaccharieramzi** [comment]
I think it's because `benchopt --version --check-editable` returns:

```
/home/zaccharie/workspace/benchOpt/benchopt/config.py:75: UserWarning: BenchOpt config file /home/zaccharie/.config/benchopt.ini is with mode 664.
As it stores sensitive information such as the github token,
it is advised to use mode 600 (user rw only).
  warnings.warn(
1.1.1.dev117 True
```

I will get rid of this warning by `chmod`-ing `.config/benchopt.ini`, but maybe there should be a way to deal with this.

**Comment by zaccharieramzi** [comment]
Yes `chmod 600 ~/.config/benchopt.ini` solved the issue. Keeping this open, since I think it should be better handled.

**Comment by mathurinm** [comment]
I can reproduce. @tomMoral should we use `output.split()[-2:]` as a fix ?
