### ISSUE TITLE
BUG - Install conda dependencies using ``benchopt install .`` fails

### ISSUE THREAD

**Issue by Badr-MOUFAD** [benchopt/benchopt#400]
This happens particularly when installing dependencies using the CLI (No error when doing that manually)

To reproduce, 
```shell
benchopt install .
```
<details>
<summary>Logs (click to expend)</summary>

```shell
(base) C:\Users\HP\Desktop\benchmarks\benchmark_elastic_net>benchopt install .
Installing 'benchmark_elastic_net' requirements
Install in the current env 'base'? [y/N]: y
# Install
Collecting packages:
- 'Enet' already available
- 'cd' already available
- 'skglm' already available
- 'sklearn' already available
- 'libsvm' already available
- 'Simulated' already available
... done
Installing required packages for:
- lightning
.../bin/bash: C:UsersHPAppDataLocalTemptmpje88g9i7: No such file or directory
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Scripts\benchopt-script.py", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "C:\Users\HP\anaconda3\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\HP\anaconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\HP\anaconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\HP\anaconda3\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\hp\desktop\celer-repo\benchopt\benchopt\cli\main.py", line 392, in install
    benchmark.install_all_requirements(
  File "c:\users\hp\desktop\celer-repo\benchopt\benchopt\benchmark.py", line 359, in install_all_requirements
    install_in_conda_env(
  File "c:\users\hp\desktop\celer-repo\benchopt\benchopt\utils\conda_env_cmd.py", line 197, in install_in_conda_env
    _run_shell_in_conda_env(
  File "c:\users\hp\desktop\celer-repo\benchopt\benchopt\utils\shell_cmd.py", line 129, in _run_shell_in_conda_env
    return _run_shell(
  File "c:\users\hp\desktop\celer-repo\benchopt\benchopt\utils\shell_cmd.py", line 67, in _run_shell
    raise RuntimeError(raise_on_error.format(output=output))
RuntimeError: Failed to conda install packages sklearn-contrib-lightning
Error:
```
</details>

It's more a platform-related issue, namely Windows. Note that the error is mainly due to a wrong path ``C:UsersHPAppDataLocalTemptmpje88g9i7`` where the backslashes were removed.

Investigating the problem (credit @mathurinm) revealed that 
https://github.com/benchopt/benchopt/blob/46e9ee4e55059c87f590e8125cf664db8f8afa5c/benchopt/utils/shell_cmd.py#L63
is potentially the source of the problem.

**Comment by mathurinm** [comment]
I'll check after thursday 10 pm

**Comment by tomMoral** [comment]
This has been fixed in benchopt 1.7
