### ISSUE TITLE
BUG `import_ctx.import_from` fails in the last benchopt version

### ISSUE THREAD

**Issue by MatDag** [benchopt/benchopt#458]
On the bilevel benchmark, when running `benchopt run .`, I get 

```
Benchopt is running
<class 'benchopt_benchmarks.benchmark_bilevel.objective.Objective'>
Traceback (most recent call last):
  File "/Users/mathieudagreou/opt/anaconda3/bin/benchopt", line 8, in <module>
    sys.exit(benchopt())
  File "/Users/mathieudagreou/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mathieudagreou/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/mathieudagreou/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mathieudagreou/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mathieudagreou/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mathieudagreou/opt/anaconda3/lib/python3.8/site-packages/benchopt/cli/main.py", line 220, in run
    benchmark.validate_objective_filters(objective_filters)
  File "/Users/mathieudagreou/opt/anaconda3/lib/python3.8/site-packages/benchopt/benchmark.py", line 84, in validate_objective_filters
    all_objectives = _list_all_parametrized_names(
  File "/Users/mathieudagreou/opt/anaconda3/lib/python3.8/site-packages/benchopt/utils/parametrized_name_mixin.py", line 116, in _list_all_parametrized_names
    cls._get_parametrized_name(**dataset_parameters)
  File "/Users/mathieudagreou/opt/anaconda3/lib/python3.8/site-packages/benchopt/utils/parametrized_name_mixin.py", line 62, in _get_parametrized_name
    return str(cls.get_instance(**parameters))
  File "/Users/mathieudagreou/opt/anaconda3/lib/python3.8/site-packages/benchopt/utils/parametrized_name_mixin.py", line 39, in get_instance
    obj = cls(**parameters)
  File "/Users/mathieudagreou/Documents/benchmark_bilevel/objective.py", line 45, in __init__
    self.inner_oracle = oracles.DataCleaningOracle
NameError: name 'oracles' is not defined
```

This seems to be caused by #451 since it works when working with the version preceding this PR.

**Comment by mathurinm** [comment]
@tomMoral fixed in #451 ? I can no longer reproduce on the bilevel benchmark with benchopt 1.3.2dev22

**Comment by tomMoral** [comment]
I am not sure, I think we fixed this in the benchmark bilevel with a workaround but not sure what happens if you import stuff from `benchmark_utils` in the `benchmark_utils` files.

**Comment by tomMoral** [comment]
Both `import_from` and `safe_import_context` have been removed. closing.
