### ISSUE TITLE
BUG dedicated env creation with `mamba` fails

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#480]
Error message :
```
Installing pip dependencies: / Ran pip subprocess with arguments:
['/home/mathurin/mambaforge/envs/benchopt_lasso/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/condaenv.7ro6jqge.requirements.txt']
Pip subprocess output:
Obtaining file:///home/mathurin/mambaforge/lib/python3.10/site-packages (from -r /tmp/condaenv.7ro6jqge.requirements.txt (line 1))

Pip subprocess error:
ERROR: file:///home/mathurin/mambaforge/lib/python3.10/site-packages (from -r /tmp/condaenv.7ro6jqge.requirements.txt (line 1)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

failed

CondaEnvException: Pip failed
```

Full stacktrace:
```
(base) ➜  lasso git:(main) ✗ benchopt install -s celer --env --recreate
Installing 'lasso' requirements
Creating conda env 'benchopt_lasso':... 
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
r/linux-64                                                  Using cache
r/noarch                                                    Using cache


Looking for: ['python=3.9', 'numpy', 'cython', 'compilers', 'pip']


Transaction

  Prefix: /home/mathurin/mambaforge/envs/benchopt_lasso

  Updating specs:

   - python=3.9
   - numpy
   - cython
   - compilers
   - pip


  Package                       Version  Build                Channel                    Size
───────────────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex                   0.1  conda_forge          conda-forge/linux-64     Cached
  + _openmp_mutex                   4.5  2_gnu                conda-forge/linux-64     Cached
  + binutils                       2.39  hdd6e379_0           conda-forge/linux-64     Cached
  + binutils_impl_linux-64         2.39  h6ceecb4_0           conda-forge/linux-64     Cached
  + binutils_linux-64              2.39  h5fc0e48_11          conda-forge/linux-64     Cached
  + bzip2                         1.0.8  h7f98852_4           conda-forge/linux-64     Cached
  + c-compiler                    1.5.1  h166bdaf_0           conda-forge/linux-64     Cached
  + ca-certificates           2022.9.24  ha878542_0           conda-forge/linux-64     Cached
  + compilers                     1.5.1  ha770c72_0           conda-forge/linux-64     Cached
  + cxx-compiler                  1.5.1  h924138e_0           conda-forge/linux-64     Cached
  + cython                      0.29.32  py39h5a03fae_1       conda-forge/linux-64     Cached
  + fortran-compiler              1.5.1  h2a4ca65_0           conda-forge/linux-64     Cached
  + gcc                          10.4.0  hb92f740_11          conda-forge/linux-64     Cached
  + gcc_impl_linux-64            10.4.0  h5231bdf_19          conda-forge/linux-64     Cached
  + gcc_linux-64                 10.4.0  h9215b83_11          conda-forge/linux-64     Cached
  + gfortran                     10.4.0  h0c96582_11          conda-forge/linux-64     Cached
  + gfortran_impl_linux-64       10.4.0  h7d168d2_19          conda-forge/linux-64     Cached
  + gfortran_linux-64            10.4.0  h69d5af5_11          conda-forge/linux-64     Cached
  + gxx                          10.4.0  hb92f740_11          conda-forge/linux-64     Cached
  + gxx_impl_linux-64            10.4.0  h5231bdf_19          conda-forge/linux-64     Cached
  + gxx_linux-64                 10.4.0  h6e491c6_11          conda-forge/linux-64     Cached
  + kernel-headers_linux-64      2.6.32  he073ed8_15          conda-forge/noarch       Cached
  + ld_impl_linux-64               2.39  hc81fddc_0           conda-forge/linux-64     Cached
  + libblas                       3.9.0  16_linux64_openblas  conda-forge/linux-64     Cached
  + libcblas                      3.9.0  16_linux64_openblas  conda-forge/linux-64     Cached
  + libffi                        3.4.2  h7f98852_5           conda-forge/linux-64     Cached
  + libgcc-devel_linux-64        10.4.0  hd38fd1e_19          conda-forge/linux-64     Cached
  + libgcc-ng                    12.2.0  h65d4601_19          conda-forge/linux-64     Cached
  + libgfortran-ng               12.2.0  h69a702a_19          conda-forge/linux-64     Cached
  + libgfortran5                 12.2.0  h337968e_19          conda-forge/linux-64     Cached
  + libgomp                      12.2.0  h65d4601_19          conda-forge/linux-64     Cached
  + liblapack                     3.9.0  16_linux64_openblas  conda-forge/linux-64     Cached
  + libnsl                        2.0.0  h7f98852_0           conda-forge/linux-64     Cached
  + libopenblas                  0.3.21  pthreads_h78a6416_3  conda-forge/linux-64     Cached
  + libsanitizer                 10.4.0  h5246dfb_19          conda-forge/linux-64     Cached
  + libsqlite                    3.39.4  h753d276_0           conda-forge/linux-64     Cached
  + libstdcxx-devel_linux-64     10.4.0  hd38fd1e_19          conda-forge/linux-64     Cached
  + libstdcxx-ng                 12.2.0  h46fd767_19          conda-forge/linux-64     Cached
  + libuuid                      2.32.1  h7f98852_1000        conda-forge/linux-64     Cached
  + libzlib                      1.2.13  h166bdaf_4           conda-forge/linux-64     Cached
  + ncurses                         6.3  h27087fc_1           conda-forge/linux-64     Cached
  + numpy                        1.23.4  py39h3d75532_1       conda-forge/linux-64     Cached
  + openssl                       3.0.7  h166bdaf_0           conda-forge/linux-64     Cached
  + pip                          22.3.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + python                       3.9.13  h2660328_0_cpython   conda-forge/linux-64     Cached
  + python_abi                      3.9  2_cp39               conda-forge/linux-64     Cached
  + readline                      8.1.2  h0f457ee_0           conda-forge/linux-64     Cached
  + setuptools                   65.5.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + sqlite                       3.39.4  h4ff8645_0           conda-forge/linux-64     Cached
  + sysroot_linux-64               2.12  he073ed8_15          conda-forge/noarch       Cached
  + tk                           8.6.12  h27826a3_0           conda-forge/linux-64     Cached
  + tzdata                        2022f  h191b570_0           conda-forge/noarch       Cached
  + wheel                        0.38.3  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + xz                            5.2.6  h166bdaf_0           conda-forge/linux-64     Cached

  Summary:

  Install: 54 packages

  Total download: 0 B

───────────────────────────────────────────────────────────────────────────────────────────────

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/home/mathurin/mambaforge/envs/benchopt_lasso/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/condaenv.7ro6jqge.requirements.txt']
Pip subprocess output:
Obtaining file:///home/mathurin/mambaforge/lib/python3.10/site-packages (from -r /tmp/condaenv.7ro6jqge.requirements.txt (line 1))

Pip subprocess error:
ERROR: file:///home/mathurin/mambaforge/lib/python3.10/site-packages (from -r /tmp/condaenv.7ro6jqge.requirements.txt (line 1)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

failed

CondaEnvException: Pip failed

failed to create the environment.
Traceback (most recent call last):
  File "/home/mathurin/mambaforge/bin/benchopt", line 8, in <module>
    sys.exit(benchopt())
  File "/home/mathurin/mambaforge/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mathurin/mambaforge/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mathurin/mambaforge/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mathurin/mambaforge/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mathurin/mambaforge/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mathurin/workspace/benchopt/benchopt/cli/main.py", line 443, in install
    create_conda_env(env_name, recreate=recreate, quiet=quiet)
  File "/home/mathurin/workspace/benchopt/benchopt/utils/conda_env_cmd.py", line 121, in create_conda_env
    _run_shell(
  File "/home/mathurin/workspace/benchopt/benchopt/utils/shell_cmd.py", line 67, in _run_shell
    raise RuntimeError(raise_on_error.format(output=output))
RuntimeError
```

**Comment by tomMoral** [comment]
The same happens with `BENCHOPT_CONDA_CMD=conda`, so it seems that the behavior of `conda` changed again...

**Comment by tomMoral** [comment]
The issue seems to be in our detection of how `benchopt` is installed, as we try to run: `pip install -e /home/mathurin/mambaforge/lib/python3.10/site-packages` instead of running on the folder from which `benchopt` is installed.
