### ISSUE TITLE
Celer installation fails 

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#5]
I run into an issue when trying to benchmark celer:
```

(base) ➜  benchOpt git:(master) benchopt bench -n 3 --max-samples 10 -s celer
Mathurin's version of Blitzl1
Installing solver Blitz in lasso:... done
Installing solver Celer in lasso:...Traceback (most recent call last):
  File "/home/mathurin/miniconda3/bin/benchopt", line 11, in <module>
    load_entry_point('benchopt', 'console_scripts', 'benchopt')()
  File "/home/mathurin/workspace/benchOpt/benchopt/cli.py", line 93, in start
    main()
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mathurin/workspace/benchOpt/benchopt/cli.py", line 80, in bench
    env_name=benchmark)
  File "/home/mathurin/workspace/benchOpt/benchopt/util.py", line 287, in install_solvers
    solver.install(env_name=env_name, force=force_install)
  File "/home/mathurin/workspace/benchOpt/benchopt/base.py", line 193, in install
    pip_install_in_env(cls.package_install, env_name=env_name)
  File "/home/mathurin/workspace/benchOpt/benchopt/util.py", line 106, in pip_install_in_env
    msg=f"Failed to pip install packages {packages}\n"
  File "/home/mathurin/workspace/benchOpt/benchopt/util.py", line 96, in _run_bash_in_env
    return _run_in_bash(script, msg=msg)
  File "/home/mathurin/workspace/benchOpt/benchopt/util.py", line 66, in _run_in_bash
    raise RuntimeError(msg.format(output=output))
RuntimeError: Failed to pip install packages ('git+https://github.com/mathurinm/celer.git',)
Error:Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-zczpjezu/

```

It works fine with the blitz solver. Updating setuptools did not fix the issue (Version: 45.1.0.post20200119), neither did removing my local install of celer. 
Any idea where it might come from ?

**Comment by mathurinm** [comment]
Specifying `logreg` makes it work:
```
(base) ➜  benchOpt git:(master) ✗ benchopt bench --max-samples 5 -n 10 logreg -s celer
Mathurin's version of Blitzl1
Installing solver Celer in logreg:...cmd=pip install -qq git+https://github.com/mathurinm/celer.git
 done
```
specifying Lasso does not work:
(base) ➜  benchOpt git:(master) ✗ benchopt bench --max-samples 5 -n 10 lasso -s celer
Mathurin's version of Blitzl1
Installing solver Celer in lasso:... cmd=pip install -qq git+https://github.com/mathurinm/celer.git
Traceback (most recent call last):
  File "/home/mathurin/miniconda3/bin/benchopt", line 11, in <module>
    load_entry_point('benchopt', 'console_scripts', 'benchopt')()
  File "/home/mathurin/workspace/benchOpt/benchopt/cli.py", line 93, in start
    main()
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mathurin/workspace/benchOpt/benchopt/cli.py", line 80, in bench
    env_name=benchmark)
  File "/home/mathurin/workspace/benchOpt/benchopt/util.py", line 288, in install_solvers
    solver.install(env_name=env_name, force=force_install)
  File "/home/mathurin/workspace/benchOpt/benchopt/base.py", line 193, in install
    pip_install_in_env(cls.package_install, env_name=env_name)
  File "/home/mathurin/workspace/benchOpt/benchopt/util.py", line 107, in pip_install_in_env
    msg=f"Failed to pip install packages {packages}\n"
  File "/home/mathurin/workspace/benchOpt/benchopt/util.py", line 96, in _run_bash_in_env
    return _run_in_bash(script, msg=msg)
  File "/home/mathurin/workspace/benchOpt/benchopt/util.py", line 66, in _run_in_bash
    raise RuntimeError(msg.format(output=output))
RuntimeError: Failed to pip install packages ('git+https://github.com/mathurinm/celer.git',)
Error:Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-6qariopi/

**Comment by tomMoral** [comment]
This should be fixed in the latest version. I am closing, feel free to reopen if this happens again.
