### ISSUE TITLE
BUG parameter that are strings containing  '/' break our parsing

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#587]
Reproduce by adding a parameter to the Lasso benchmark
```python
    parameters = {
        'fit_intercept': [True, False],
        'reg': [.5, .1, .05],
        'data': ["path/to/stuff"],
    }
```

```python
Traceback (most recent call last):
  File "/home/mathurin/mambaforge/bin/benchopt", line 8, in <module>
    sys.exit(benchopt())
  File "/home/mathurin/mambaforge/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mathurin/mambaforge/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mathurin/mambaforge/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mathurin/mambaforge/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mathurin/mambaforge/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mathurin/workspace/benchopt/benchopt/cli/main.py", line 222, in run
    benchmark.validate_objective_filters(objective_filters)
  File "/home/mathurin/workspace/benchopt/benchopt/benchmark.py", line 91, in validate_objective_filters
    _validate_patterns(all_objectives, objective_filters,
  File "/home/mathurin/workspace/benchopt/benchopt/benchmark.py", line 655, in _validate_patterns
    matched = any([is_matched(name, [p]) for name in all_names])
  File "/home/mathurin/workspace/benchopt/benchopt/benchmark.py", line 655, in <listcomp>
    matched = any([is_matched(name, [p]) for name in all_names])
  File "/home/mathurin/workspace/benchopt/benchopt/benchmark.py", line 531, in is_matched
    name = _extract_options(name)[0]
  File "/home/mathurin/workspace/benchopt/benchopt/benchmark.py", line 579, in _extract_options
    result = _extract_parameters(match)
  File "/home/mathurin/workspace/benchopt/benchopt/benchmark.py", line 644, in _extract_parameters
    raise ValueError(f"Invalid name '{original}', evaluated as {string}.")
ValueError: Invalid name 'data=path/to/stuff,fit_intercept=True,reg=0.5', evaluated as {'data':'path'/'to'/'stuff','fit_intercept':True,'reg':0.5}.

```

@leonzheng2

**Comment by mathurinm** [comment]
Reproduce with 
```
from benchopt.benchmark import _extract_parameters
_extract_parameters("data=path/to/stuff,reg=0.1")
```

This works:
```
_extract_parameters(data='path/to/stuff',reg=0.1")
```

The problem is that it's the first case which is triggered by `'data': ["path/to/stuff"],`

**Comment by agonon** [comment]
![image](https://github.com/benchopt/benchopt/assets/32032118/eb527928-c454-4214-ae95-14fe40ae8c6b)

**Comment by tomMoral** [comment]
For the second part @agonon, for any CLI, one parameter is delimited by space so it is hard to disentangle between the fact that `adamw[max_epoch=90, lr=0.001]` is a single argument and the fact that you have another argument after the space.
The solution to pass parameters with a space is to add quotes `"` around it: `"adamw[max_epoch=90, lr=0.001]"adamw[max_epoch=90, lr=0.001]"` is considered as a single parameter. It is not ideal but I am not sure we have a better solution for now.

This is in part discussed in #574 

For the first part, we need to find a good solution to make the parsing more reliable.
