### ISSUE TITLE
[BUG] ```benchopt install``` is unable to detect conda env

### ISSUE THREAD

**Issue by pbarbarant** [benchopt/benchopt#677]
It appears that the current version of benchopt is unable to detect conda environments which results in ```benchopt install .``` failing.
Tested on ```linux-64```, on an updated version of conda.
```
(benchopt) pbarbara@drago5:/data/parietal/store3/work/pbarbara/fmralign_benchmark_old$ benchopt install .
Traceback (most recent call last):
  File "/data/parietal/store3/work/pbarbara/anaconda3/envs/benchopt/bin/benchopt", line 8, in <module>
    sys.exit(benchopt())
             ^^^^^^^^^^
  File "/data/parietal/store3/work/pbarbara/anaconda3/envs/benchopt/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/parietal/store3/work/pbarbara/anaconda3/envs/benchopt/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/parietal/store3/work/pbarbara/anaconda3/envs/benchopt/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/parietal/store3/work/pbarbara/anaconda3/envs/benchopt/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/parietal/store3/work/pbarbara/anaconda3/envs/benchopt/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/store3/work/pbarbara/benchopt/benchopt/cli/main.py", line 410, in install
    raise RuntimeError(
RuntimeError: No conda environment is activated. You should be in a conda environment to use 'benchopt install'.
```

**Comment by tomMoral** [comment]
which version of conda?

**Comment by pbarbarant** [comment]
``conda info`` gives me:
```
conda version : 23.11.0
conda-build version : 3.28.2
```

**Comment by pbarbarant** [comment]
Any recent update @tommoral ? 🏔️

**Comment by ambroiseodt** [comment]
Hello @pbarbarant @tomMoral  , I also had this issue. I was using a conda env in miniforge3. When I switched to a conda env in miniconda3, it worked fine.

**Comment by pbarbarant** [comment]
> Hello @pbarbarant @tomMoral , I also had this issue. I was using a conda env in miniforge3. When I switched to a conda env in miniconda3, it worked fine.

I just moved to a micromamba config (version `1.5.8`) and I get the same error.

**Comment by mathurinm** [comment]
I think the culprit may be `https://github.com/benchopt/benchopt/blob/main/benchopt/utils/conda_env_cmd.py#L237` because as tested on @ambroiseodt computer, the `conda` package is not installed in miniforge

**Comment by ambroiseodt** [comment]
@mathurinm I did ```mamba install conda``` inside of the miniforge env and it worked fine now I can ```benchopt -s skglm``` easily. Thanks!

**Comment by pbarbarant** [comment]
It appears that the issue was caused by a discrepancy in the paths between my interpreter and my micromanba env location which prevented benchopt from detecting the activated environment.
