### ISSUE TITLE
Bug with Nested config files for solvers

### ISSUE THREAD

**Issue by antoinedemathelin** [benchopt/benchopt#715]
Hi,
I encounter a bug when using nested config files for solver:

config:
```
solver:
  - NO_DA_SOURCE_ONLY:
	    param_grid:
	       - finalestimator__estimator_name:
	            - LR_C10.0
	            - LR_C100.0
```

I get this error:

```
20NewsGroups[preprocessing=min_hash,source_target=('rec', 'talk')]
  |--SKADA Domain Adaptation Benchmark
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Scripts\benchopt.exe\__main__.py", line 7, in <module>
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\benchopt\cli\main.py", line 239, in run
    run_benchmark(
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\benchopt\runner.py", line 355, in run_benchmark
    results = Parallel(n_jobs=n_jobs)(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\joblib\parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\joblib\parallel.py", line 1844, in _get_sequential_output
    for func, args, kwargs in iterable:
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\benchopt\runner.py", line 355, in <genexpr>
    results = Parallel(n_jobs=n_jobs)(
                                     ^
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\benchopt\benchmark.py", line 591, in get_all_runs
    output.set(solver=solver, i_solver=i_solver)
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\benchopt\utils\terminal_output.py", line 104, in set
    self.solver_tag = colorify(f"    |--{solver}:")
                               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\Anaconda3\envs\skadabench\Lib\site-packages\benchopt\utils\parametrized_name_mixin.py", line 67, in __repr__
    out += f"[{self.parameter_template}]".format(**self._parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: "'finalestimator__estimator_name'"
```

**Comment by tomMoral** [comment]
Solved with #716
