### ISSUE TITLE
Running benchmark_logreg_l2 fails to install sklearn

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#76]
I freshly pulled this master, did the `pip install -e .`, had no preexisting benchopt_ conda env, and tried to run the sklearn solver. Install fails and I get a surprising `command not found benchopt` after.

Steps to reproduce (?):
fresh install of benchopt, go to benchmark_logreg_l2 and try to `benchopt run . -s sklearn`

```
(base) ➜  benchmark_logreg_l2 git:(master) benchopt run . -s sklearn      
Could not generate requirement for distribution -cikit-learn 0.23.0 (/home/mathurin/miniconda3/lib/python3.7/site-packages): Parse error at "'-cikit-l'": Expected W:(abcd...)
Installing Simulated in benchopt_:... failed
/home/mathurin/workspace/benchOpt/benchopt/util.py:156: UserWarning: Some solvers were not successfully installed, and will thus be ignored. Use 'export BENCHO_RAISE_INSTALL_ERROR=true' to stop at any installation failure and print the traceback.
  UserWarning
Installing sklearn in benchopt_:... failed
Installing sklearn in benchopt_:... failed
Installing sklearn in benchopt_:... failed
/tmp/tmpw6thjflk:4: command not found: benchopt
```

**Comment by mathurinm** [comment]
Debug output:
```
(base) ➜  benchmark_logreg_l2 git:(master) BENCHO_DEBUG=1 benchopt run . -s sklearn
Could not generate requirement for distribution -cikit-learn 0.23.0 (/home/mathurin/miniconda3/lib/python3.7/site-packages): Parse error at "'-cikit-l'": Expected W:(abcd...)
set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
which python
Creating conda env benchopt_:...set -e
conda env create  -n benchopt_ -f /tmp/tmptrq2j_ur.yml
 failed to create the environment.
Traceback (most recent call last):
  File "/home/mathurin/miniconda3/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mathurin/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mathurin/workspace/benchOpt/benchopt/cli.py", line 94, in run
    create_conda_env(env_name, recreate=recreate)
  File "/home/mathurin/workspace/benchOpt/benchopt/utils/shell_cmd.py", line 152, in create_conda_env
    capture_stdout=True, raise_on_error=True
  File "/home/mathurin/workspace/benchOpt/benchopt/utils/shell_cmd.py", line 83, in _run_shell
    raise RuntimeError(raise_on_error.format(output=output))
RuntimeError: Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... Ran pip subprocess with arguments:
['/home/mathurin/miniconda3/envs/benchopt_/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/condaenv.p8tgu6go.requirements.txt']
Pip subprocess output:
Obtaining benchopt from git+git@github.com:mathurinm/benchOpt.git@659645cf1e44ed809df8098a04b84f97c162d508#egg=benchopt (from -r /tmp/condaenv.p8tgu6go.requirements.txt (line 1))
  Updating ./src/benchopt clone (to revision 659645cf1e44ed809df8098a04b84f97c162d508)

failed
Pip subprocess error:
  DEPRECATION: This form of VCS requirement is being deprecated: git+git@github.com:mathurinm/benchOpt.git@659645cf1e44ed809df8098a04b84f97c162d508#egg=benchopt. pip 21.0 will remove support for this functionality. A possible replacement is git+https://git@example.com/..., git+ssh://git@example.com/..., or the insecure git+git://git@example.com/.... You can find discussion regarding this at https://github.com/pypa/pip/issues/7554.
ERROR: Command errored out with exit status 128: git reset --hard -q 659645cf1e44ed809df8098a04b84f97c162d508 Check the logs for full command output.


CondaEnvException: Pip failed
```

**Comment by mathurinm** [comment]
First error with "-cikit" seemed unrelated: I fixed it but still cannot install. Also, I pulled master, but it seems that parametrized class is still being installed several times
```
(base) ➜  benchmark_logreg_l2 git:(master) ls /home/mathurin/miniconda3/lib/python3.7/site-packages | grep ciki
~cikit_learn-0.22.dist-info
~cikit_learn-0.23.0.dist-info
~cikit_learn.libs
scikit_learn-0.23.2.dist-info
scikit-learn.egg-link
(base) ➜  benchmark_logreg_l2 git:(master) rm -r /home/mathurin/miniconda3/lib/python3.7/site-packages/~cikit*
(base) ➜  benchmark_logreg_l2 git:(master) ls /home/mathurin/miniconda3/lib/python3.7/site-packages | grep ciki
scikit_learn-0.23.2.dist-info
scikit-learn.egg-link
(base) ➜  benchmark_logreg_l2 git:(master) BENCHO_DEBUG=1 benchopt run . -s sklearn                            
set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
which python
set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
benchopt check-install /home/mathurin/workspace/benchmark_logreg_l2/datasets/simulated.py Dataset
Installing Simulated in benchopt_:...set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
benchopt check-install /home/mathurin/workspace/benchmark_logreg_l2/datasets/simulated.py Dataset
 failed
/home/mathurin/workspace/benchOpt/benchopt/util.py:159: UserWarning: Some solvers were not successfully installed, and will thus be ignored. Use 'export BENCHO_RAISE_INSTALL_ERROR=true' to stop at any installation failure and print the traceback.
  UserWarning
set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
benchopt check-install /home/mathurin/workspace/benchmark_logreg_l2/solvers/sklearn.py Solver
Installing sklearn in benchopt_:...set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
conda install -y scikit-learn
set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
benchopt check-install /home/mathurin/workspace/benchmark_logreg_l2/solvers/sklearn.py Solver
 failed
set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
benchopt run . --local --n-repetitions 5 --max-runs 100 --timeout 100 -s sklearn     
/tmp/tmpk5og5c30:4: command not found: benchopt
```

**Comment by mathurinm** [comment]
Solved with latest merged PRs + `conda env remove benchopt_` and start from scratch.

We may want to specify in the doc that everything is installed in a conda env named banchopt_, wdyt ? where ?

**Comment by tomMoral** [comment]
It is indeed installed only once, there is 2 checks, one at before the install and one after to check if the install was successful:

```
set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
benchopt check-install /home/mathurin/workspace/benchmark_logreg_l2/solvers/sklearn.py Solver
Installing sklearn in benchopt_:...set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
conda install -y scikit-learn
set -e
eval "$(conda shell.bash hook)"
conda activate benchopt_
benchopt check-install /home/mathurin/workspace/benchmark_logreg_l2/solvers/sklearn.py Solver
 failed

**Comment by tomMoral** [comment]
For the environemnt name, it should be `benchopt_BENCHMARKNAME` but it failed to find the correct name of the bench when it is run with `benchopt run .`. I have a fix for this.
